In [1]:
# Some resources:
# http://www.nltk.org/book/
# http://victoria.lviv.ua/html/fl5/NaturalLanguageProcessingWithPython.pdf
# https://www.analyticsvidhya.com/blog/2017/04/natural-language-processing-made-easy-using-spacy-%E2%80%8Bin-python/
# https://radimrehurek.com/gensim/tutorial.html
# http://textacy.readthedocs.io/en/latest/

In [1]:
# download the file and extract to the same directory as this notebook
# http://ai.stanford.edu/~amaas/data/sentiment/
import glob

neg_reviews = []
pos_reviews = []

for filename in glob.glob('./aclImdb/train/neg/*.txt'):
    with open(filename) as infile:
        neg_reviews.append(infile.read())
for filename in glob.glob('./aclImdb/train/pos/*.txt'):
    with open(filename) as infile:
        pos_reviews.append(infile.read())
        
print len(neg_reviews)
len(pos_reviews)

12500


12500

In [2]:
neg_reviews[0]

'Trying to conceive of something as insipid as THE SENTINEL would be pretty difficult. The problems are many. The result is terrible and loaded with plot holes.<br /><br />Michael Douglas stars as Pete Garrison, a Secret Service agent who "took one" for Reagan during the attempt on his life. Years later we find Pete assigned to the Whitehouse Family, mainly as a guard for the First Lady (Kim Basinger, L.A. CONFIDENTIAL). Troubles arise as we see Pete\'s close involvement with the First Lady, and a sudden threat against the President himself (David Rasche, UNITED 93). When Pete fails a polygraph test, he\'s singled out as a disgruntled agent by investigator David Breckinridge (Kiefer Sutherland, 24 TV series).<br /><br />As the presidential assassination plot unfolds, Pete finds himself on the run from his own people. His only confidant is the First Lady, and she\'s reluctant to tell anyone about their affections for one another (which is why Pete failed the polygraph in the first place

In [3]:
import bs4
soup = bs4.BeautifulSoup(neg_reviews[0], "lxml")
soup.text

u'Trying to conceive of something as insipid as THE SENTINEL would be pretty difficult. The problems are many. The result is terrible and loaded with plot holes.Michael Douglas stars as Pete Garrison, a Secret Service agent who "took one" for Reagan during the attempt on his life. Years later we find Pete assigned to the Whitehouse Family, mainly as a guard for the First Lady (Kim Basinger, L.A. CONFIDENTIAL). Troubles arise as we see Pete\'s close involvement with the First Lady, and a sudden threat against the President himself (David Rasche, UNITED 93). When Pete fails a polygraph test, he\'s singled out as a disgruntled agent by investigator David Breckinridge (Kiefer Sutherland, 24 TV series).As the presidential assassination plot unfolds, Pete finds himself on the run from his own people. His only confidant is the First Lady, and she\'s reluctant to tell anyone about their affections for one another (which is why Pete failed the polygraph in the first place). But is Pete really i

In [4]:
print soup.text

Trying to conceive of something as insipid as THE SENTINEL would be pretty difficult. The problems are many. The result is terrible and loaded with plot holes.Michael Douglas stars as Pete Garrison, a Secret Service agent who "took one" for Reagan during the attempt on his life. Years later we find Pete assigned to the Whitehouse Family, mainly as a guard for the First Lady (Kim Basinger, L.A. CONFIDENTIAL). Troubles arise as we see Pete's close involvement with the First Lady, and a sudden threat against the President himself (David Rasche, UNITED 93). When Pete fails a polygraph test, he's singled out as a disgruntled agent by investigator David Breckinridge (Kiefer Sutherland, 24 TV series).As the presidential assassination plot unfolds, Pete finds himself on the run from his own people. His only confidant is the First Lady, and she's reluctant to tell anyone about their affections for one another (which is why Pete failed the polygraph in the first place). But is Pete really innoce

In [5]:
import pyprind
pbar = pyprind.ProgBar(12500)
for index in range(12500):
    neg_reviews[index] = bs4.BeautifulSoup(neg_reviews[index], 'lxml').text
    pos_reviews[index] = bs4.BeautifulSoup(pos_reviews[index], 'lxml').text
    pbar.update()

0%                          100%
[##############################] | ETA: 00:00:00
Total time elapsed: 00:01:29


In [6]:
print neg_reviews[1]

I'm just quite disappointed with "Soul Survivors". It doesn't worth even a comment in this forum. The script is very poor as well as all the "acting" and for our entertainment it features a pointless plot.Please, do yourselves a favor! Be a real "Survivor"...Don't waste your time in this piece of crap! Someday you'll thank me!


In [7]:
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) + ' ' + ' '.join(emoticons).replace('-', '')
    return text.strip()

In [8]:
preprocessor('<test> Hey guys!!1! :)</test> This is a test :P lolz')

'hey guys 1 this is a test p lolz :) :P'

In [52]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining and the weather is sweet'])
bag = count.fit_transform(docs)
print count.vocabulary_
print bag.toarray()

{u'and': 0, u'weather': 6, u'sweet': 4, u'sun': 3, u'is': 1, u'the': 5, u'shining': 2}
[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [47]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/cognizac/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [9]:
from nltk.corpus import stopwords
stops = stopwords.words('english')

In [10]:
stops

[u'i',
 u'me',
 u'my',
 u'myself',
 u'we',
 u'our',
 u'ours',
 u'ourselves',
 u'you',
 u'your',
 u'yours',
 u'yourself',
 u'yourselves',
 u'he',
 u'him',
 u'his',
 u'himself',
 u'she',
 u'her',
 u'hers',
 u'herself',
 u'it',
 u'its',
 u'itself',
 u'they',
 u'them',
 u'their',
 u'theirs',
 u'themselves',
 u'what',
 u'which',
 u'who',
 u'whom',
 u'this',
 u'that',
 u'these',
 u'those',
 u'am',
 u'is',
 u'are',
 u'was',
 u'were',
 u'be',
 u'been',
 u'being',
 u'have',
 u'has',
 u'had',
 u'having',
 u'do',
 u'does',
 u'did',
 u'doing',
 u'a',
 u'an',
 u'the',
 u'and',
 u'but',
 u'if',
 u'or',
 u'because',
 u'as',
 u'until',
 u'while',
 u'of',
 u'at',
 u'by',
 u'for',
 u'with',
 u'about',
 u'against',
 u'between',
 u'into',
 u'through',
 u'during',
 u'before',
 u'after',
 u'above',
 u'below',
 u'to',
 u'from',
 u'up',
 u'down',
 u'in',
 u'out',
 u'on',
 u'off',
 u'over',
 u'under',
 u'again',
 u'further',
 u'then',
 u'once',
 u'here',
 u'there',
 u'when',
 u'where',
 u'why',
 u'how',
 u'all

In [11]:
def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stops])

In [12]:
text = remove_stopwords(neg_reviews[1].lower())
text

u'i\'m quite disappointed "soul survivors". doesn\'t worth even comment forum. script poor well "acting" entertainment features pointless plot.please, favor! real "survivor"...don\'t waste time piece crap! someday you\'ll thank me!'

In [54]:
import textacy

remove_stopwords(textacy.preprocess.preprocess_text(neg_reviews[1], no_contractions=True, no_punct=True, lowercase=True))

u'quite disappointed soul survivors worth even comment forum script poor well acting entertainment features pointless plotplease favor real survivordo waste time piece crap someday thank'

In [55]:
text = textacy.preprocess.preprocess_text(neg_reviews[1], no_contractions=True, no_punct=True, lowercase=True)
text

u'i am just quite disappointed with soul survivors it does not worth even a comment in this forum the script is very poor as well as all the acting and for our entertainment it features a pointless plotplease do yourselves a favor be a real survivordo not waste your time in this piece of crap someday you will thank me'

In [57]:
doc = textacy.Doc(text)

In [58]:
doc.to_bag_of_words(as_strings=True, normalize='lemma')

{u'-PRON-': 7,
 u'acting': 1,
 u'comment': 1,
 u'crap': 1,
 u'disappointed': 1,
 u'entertainment': 1,
 u'favor': 1,
 u'feature': 1,
 u'forum': 1,
 u'piece': 1,
 u'plotplease': 1,
 u'pointless': 1,
 u'poor': 1,
 u'real': 1,
 u'script': 1,
 u'someday': 1,
 u'soul': 1,
 u'survivor': 1,
 u'survivordo': 1,
 u'thank': 1,
 u'time': 1,
 u'waste': 1,
 u'worth': 1}

In [66]:
[ng for ng in textacy.extract.ngrams(doc, n=2, filter_stops=False)]

[i am,
 am just,
 just quite,
 quite disappointed,
 disappointed with,
 with soul,
 soul survivors,
 survivors it,
 it does,
 does not,
 not worth,
 worth even,
 even a,
 a comment,
 comment in,
 in this,
 this forum,
 forum the,
 the script,
 script is,
 is very,
 very poor,
 poor as,
 as well,
 well as,
 as all,
 all the,
 the acting,
 acting and,
 and for,
 for our,
 our entertainment,
 entertainment it,
 it features,
 features a,
 a pointless,
 pointless plotplease,
 plotplease do,
 do yourselves,
 yourselves a,
 a favor,
 favor be,
 be a,
 a real,
 real survivordo,
 survivordo not,
 not waste,
 waste your,
 your time,
 time in,
 in this,
 this piece,
 piece of,
 of crap,
 crap someday,
 someday you,
 you will,
 will thank,
 thank me]

In [68]:
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2), min_df=1)
analyze = bigram_vectorizer.build_analyzer()
analyze('Bi-grams are cool!')

[u'bi grams', u'grams are', u'are cool']

In [71]:
bg = bigram_vectorizer.fit_transform(neg_reviews)

bg.get_shape()

(12500, 829466)

In [72]:
bigram_vectorizer.get_feature_names()

[u'00 am',
 u'00 and',
 u'00 back',
 u'00 bin',
 u'00 budget',
 u'00 dollars',
 u'00 feet',
 u'00 for',
 u'00 in',
 u'00 it',
 u'00 keoni',
 u'00 know',
 u'00 loan',
 u'00 making',
 u'00 need',
 u'00 on',
 u'00 one',
 u'00 or',
 u'00 outlay',
 u'00 pm',
 u'00 price',
 u'00 rental',
 u'00 replacement',
 u'00 second',
 u'00 several',
 u'00 so',
 u'00 spent',
 u'00 they',
 u'00 to',
 u'00 will',
 u'00 you',
 u'000 00',
 u'000 000',
 u'000 10',
 u'000 and',
 u'000 annual',
 u'000 as',
 u'000 audience',
 u'000 bc',
 u'000 bet',
 u'000 budget',
 u'000 bullets',
 u'000 but',
 u'000 by',
 u'000 can',
 u'000 commands',
 u'000 continuity',
 u'000 corpses',
 u'000 could',
 u'000 crack',
 u'000 dollars',
 u'000 fathoms',
 u'000 feet',
 u'000 film',
 u'000 films',
 u'000 fingers',
 u'000 first',
 u'000 frock',
 u'000 from',
 u'000 get',
 u'000 gold',
 u'000 grand',
 u'000 he',
 u'000 heart',
 u'000 how',
 u'000 id',
 u'000 if',
 u'000 in',
 u'000 is',
 u'000 it',
 u'000 lbs',
 u'000 leagues',
 u'00

In [93]:
t = bg[:, 0] > 0
np.array(neg_reviews)[t.toarray().reshape(12500,)]

array([ u'I saw this film when it was first released. The memory of how bad it was has stayed with me almost forty years. I didn\'t want to trust my own sentiments about the movie when I saw it, so I consulted a movie review published in a major metropolitan newspaper the next day- sentiment confirmed, the reviewer wrote that the movie was incoherent, indecipherable, and uninspiring. A little research reveals that the producer was star Leslie Caron\'s husband, thus the whiff of nepotism suggests the beginning for this awful film. The film\'s roster of many capable actors - Caron, Warren Oates, Scatman Crothers, Gloria Grahame, and James Sikking among others - suggests that it holds some promise. But the death of this film is attributable to its terrible screenplay. The "mystery" implicated is so obscure and so little revealed throughout the film that the viewer is left perplexed from scene to scene. The movie seems torn between being a detective mystery and an espionage thriller, but n

In [41]:
[t for t in text.tokens]

[Trying,
 to,
 conceive,
 of,
 something,
 as,
 insipid,
 as,
 THE,
 SENTINEL,
 would,
 be,
 pretty,
 difficult,
 .,
 The,
 problems,
 are,
 many,
 .,
 The,
 result,
 is,
 terrible,
 and,
 loaded,
 with,
 plot,
 holes,
 .,
 Michael,
 Douglas,
 stars,
 as,
 Pete,
 Garrison,
 ,,
 a,
 Secret,
 Service,
 agent,
 who,
 ",
 took,
 one,
 ",
 for,
 Reagan,
 during,
 the,
 attempt,
 on,
 his,
 life,
 .,
 Years,
 later,
 we,
 find,
 Pete,
 assigned,
 to,
 the,
 Whitehouse,
 Family,
 ,,
 mainly,
 as,
 a,
 guard,
 for,
 the,
 First,
 Lady,
 (,
 Kim,
 Basinger,
 ,,
 L.A.,
 CONFIDENTIAL,
 ),
 .,
 Troubles,
 arise,
 as,
 we,
 see,
 Pete,
 's,
 close,
 involvement,
 with,
 the,
 First,
 Lady,
 ,,
 and,
 a,
 sudden,
 threat,
 against,
 the,
 President,
 himself,
 (,
 David,
 Rasche,
 ,,
 UNITED,
 93,
 ),
 .,
 When,
 Pete,
 fails,
 a,
 polygraph,
 test,
 ,,
 he,
 's,
 singled,
 out,
 as,
 a,
 disgruntled,
 agent,
 by,
 investigator,
 David,
 Breckinridge,
 (,
 Kiefer,
 Sutherland,
 ,,
 24,
 TV,
 series)

In [42]:
[s for s in text.sents]

[Trying to conceive of something as insipid as THE SENTINEL would be pretty difficult.,
 The problems are many.,
 The result is terrible and loaded with plot holes.,
 Michael Douglas stars as Pete Garrison, a Secret Service agent who "took one" for Reagan during the attempt on his life.,
 Years later we find Pete assigned to the Whitehouse Family, mainly as a guard for the First Lady (Kim Basinger, L.A. CONFIDENTIAL).,
 Troubles arise as we see Pete's close involvement with the First Lady, and a sudden threat against the President himself (David Rasche, UNITED 93).,
 When Pete fails a polygraph test, he's singled out as a disgruntled agent by investigator David Breckinridge (Kiefer Sutherland, 24 TV series).As the presidential assassination plot unfolds, Pete finds himself on the run from his own people.,
 His only confidant is the First Lady, and she's reluctant to tell anyone about their affections for one another (which is why Pete failed the polygraph in the first place).,
 But is 